version: '2'

services:
  parse:
    image: vegidio/parse
    environment:
      - DB_HOST=mongo:27017
      - MASTER_KEY=123456
      - APP_IDS=app1,app2
      - SERVER_URL=http://localhost:1337
      - DASHBOARD_USERNAME=admin
      - DASHBOARD_PASSWORD=password
    links:
      - mongo:mongo
    ports:
      - 1337:1337

  mongo:
    image: mongo
    ports:
      - 27017:27017
